# with open("kunal.txt") as f:
#     a = f.read(7)
#     print(a)


x = (input ('''Kunal Health Care System

for shakti`s Health, press 1

for sayam`s Health, press 2

for chirag`s Health, press 3'''))


if (x=='1'):
    print("Body Builder", "Protein Wala")
elif (x=='2'):
    print("Nothing to tell about you,you failed")
elif (x=='3'):
    print("Tere baare me bhi kya khe",'BHIL')
else:
    print("shi number to daal bhai")